export const chickenMenu = [
    {
      id:1,
      title: "Chicken Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "130",
      originalPrice: "160",
    },
    {
        id:2,
        title: "Chicken Briyani",
        description:"Amazing Briyani Served With Raita and Curry",
        discountedPrice: "130",
        originalPrice: "160",
      },
      {
        id:3,
        title: "Chicken Briyani",
        description:"Amazing Briyani Served With Raita and Curry",
        discountedPrice: "120",
        originalPrice: "160",
      },
      {
        id:4,
        title: "Chicken Briyani",
        description:"Amazing Briyani Served With Raita and Curry",
        discountedPrice: "120",
        originalPrice: "160",
      },
      {
        id:5,
        title: "Chicken Briyani",
        description:"Amazing Briyani Served With Raita and Curry",
        discountedPrice: "120",
        originalPrice: "160",
      },
      {
        id:6,
        title: "Chicken Briyani",
        description:"Amazing Briyani Served With Raita and Curry",
        discountedPrice: "120",
        originalPrice: "160",
      },
      {
        id:7,
        title: "Chicken Briyani",
        description:"Amazing Briyani Served With Raita and Curry",
        discountedPrice: "120",
        originalPrice: "160",
      },
      {
        id:8,
        title: "Chicken Briyani",
        description:"Amazing Briyani Served With Raita and Curry",
        discountedPrice: "120",
        originalPrice: "160",
      },

]

export const eggMenu = [
  {
    id:1,
    title: "egg Briyani",
    description:"Amazing Briyani Served With Raita and Curry",
    discountedPrice: "120",
    originalPrice: "160",
  },
  {
      id:2,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:3,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:4,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:5,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:6,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:7,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:8,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
]

export const rotiMenu = [
  {
    id:1,
    title: "egg Briyani",
    description:"Amazing Briyani Served With Raita and Curry",
    discountedPrice: "120",
    originalPrice: "160",
  },
  {
      id:2,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:3,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:4,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:5,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:6,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:7,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:8,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
]

export const riceMenu = [
  {
    id:1,
    title: "egg Briyani",
    description:"Amazing Briyani Served With Raita and Curry",
    discountedPrice: "120",
    originalPrice: "160",
  },
  {
      id:2,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:3,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:4,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:5,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:6,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:7,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
    {
      id:8,
      title: "egg Briyani",
      description:"Amazing Briyani Served With Raita and Curry",
      discountedPrice: "120",
      originalPrice: "160",
    },
]